require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CostosController do

  # This should return the minimal set of attributes required to create a valid
  # Costo. As you add validations to Costo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "titulo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CostosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all costos as @costos" do
      costo = Costo.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:costos)).to eq([costo])
    end
  end

  describe "GET show" do
    it "assigns the requested costo as @costo" do
      costo = Costo.create! valid_attributes
      get :show, {:id => costo.to_param}, valid_session
      expect(assigns(:costo)).to eq(costo)
    end
  end

  describe "GET new" do
    it "assigns a new costo as @costo" do
      get :new, {}, valid_session
      expect(assigns(:costo)).to be_a_new(Costo)
    end
  end

  describe "GET edit" do
    it "assigns the requested costo as @costo" do
      costo = Costo.create! valid_attributes
      get :edit, {:id => costo.to_param}, valid_session
      expect(assigns(:costo)).to eq(costo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Costo" do
        expect {
          post :create, {:costo => valid_attributes}, valid_session
        }.to change(Costo, :count).by(1)
      end

      it "assigns a newly created costo as @costo" do
        post :create, {:costo => valid_attributes}, valid_session
        expect(assigns(:costo)).to be_a(Costo)
        expect(assigns(:costo)).to be_persisted
      end

      it "redirects to the created costo" do
        post :create, {:costo => valid_attributes}, valid_session
        expect(response).to redirect_to(Costo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved costo as @costo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Costo.any_instance.stub(:save).and_return(false)
        post :create, {:costo => { "titulo" => "invalid value" }}, valid_session
        expect(assigns(:costo)).to be_a_new(Costo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Costo.any_instance.stub(:save).and_return(false)
        post :create, {:costo => { "titulo" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested costo" do
        costo = Costo.create! valid_attributes
        # Assuming there are no other costos in the database, this
        # specifies that the Costo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Costo).to receive(:update).with({ "titulo" => "MyString" })
        put :update, {:id => costo.to_param, :costo => { "titulo" => "MyString" }}, valid_session
      end

      it "assigns the requested costo as @costo" do
        costo = Costo.create! valid_attributes
        put :update, {:id => costo.to_param, :costo => valid_attributes}, valid_session
        expect(assigns(:costo)).to eq(costo)
      end

      it "redirects to the costo" do
        costo = Costo.create! valid_attributes
        put :update, {:id => costo.to_param, :costo => valid_attributes}, valid_session
        expect(response).to redirect_to(costo)
      end
    end

    describe "with invalid params" do
      it "assigns the costo as @costo" do
        costo = Costo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Costo.any_instance.stub(:save).and_return(false)
        put :update, {:id => costo.to_param, :costo => { "titulo" => "invalid value" }}, valid_session
        expect(assigns(:costo)).to eq(costo)
      end

      it "re-renders the 'edit' template" do
        costo = Costo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Costo.any_instance.stub(:save).and_return(false)
        put :update, {:id => costo.to_param, :costo => { "titulo" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested costo" do
      costo = Costo.create! valid_attributes
      expect {
        delete :destroy, {:id => costo.to_param}, valid_session
      }.to change(Costo, :count).by(-1)
    end

    it "redirects to the costos list" do
      costo = Costo.create! valid_attributes
      delete :destroy, {:id => costo.to_param}, valid_session
      expect(response).to redirect_to(costos_url)
    end
  end

end
