require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DuplasController do

  # This should return the minimal set of attributes required to create a valid
  # Dupla. As you add validations to Dupla, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DuplasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all duplas as @duplas" do
      dupla = Dupla.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:duplas)).to eq([dupla])
    end
  end

  describe "GET show" do
    it "assigns the requested dupla as @dupla" do
      dupla = Dupla.create! valid_attributes
      get :show, {:id => dupla.to_param}, valid_session
      expect(assigns(:dupla)).to eq(dupla)
    end
  end

  describe "GET new" do
    it "assigns a new dupla as @dupla" do
      get :new, {}, valid_session
      expect(assigns(:dupla)).to be_a_new(Dupla)
    end
  end

  describe "GET edit" do
    it "assigns the requested dupla as @dupla" do
      dupla = Dupla.create! valid_attributes
      get :edit, {:id => dupla.to_param}, valid_session
      expect(assigns(:dupla)).to eq(dupla)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dupla" do
        expect {
          post :create, {:dupla => valid_attributes}, valid_session
        }.to change(Dupla, :count).by(1)
      end

      it "assigns a newly created dupla as @dupla" do
        post :create, {:dupla => valid_attributes}, valid_session
        expect(assigns(:dupla)).to be_a(Dupla)
        expect(assigns(:dupla)).to be_persisted
      end

      it "redirects to the created dupla" do
        post :create, {:dupla => valid_attributes}, valid_session
        expect(response).to redirect_to(Dupla.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dupla as @dupla" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dupla.any_instance.stub(:save).and_return(false)
        post :create, {:dupla => { "nombre" => "invalid value" }}, valid_session
        expect(assigns(:dupla)).to be_a_new(Dupla)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dupla.any_instance.stub(:save).and_return(false)
        post :create, {:dupla => { "nombre" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dupla" do
        dupla = Dupla.create! valid_attributes
        # Assuming there are no other duplas in the database, this
        # specifies that the Dupla created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Dupla).to receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => dupla.to_param, :dupla => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested dupla as @dupla" do
        dupla = Dupla.create! valid_attributes
        put :update, {:id => dupla.to_param, :dupla => valid_attributes}, valid_session
        expect(assigns(:dupla)).to eq(dupla)
      end

      it "redirects to the dupla" do
        dupla = Dupla.create! valid_attributes
        put :update, {:id => dupla.to_param, :dupla => valid_attributes}, valid_session
        expect(response).to redirect_to(dupla)
      end
    end

    describe "with invalid params" do
      it "assigns the dupla as @dupla" do
        dupla = Dupla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dupla.any_instance.stub(:save).and_return(false)
        put :update, {:id => dupla.to_param, :dupla => { "nombre" => "invalid value" }}, valid_session
        expect(assigns(:dupla)).to eq(dupla)
      end

      it "re-renders the 'edit' template" do
        dupla = Dupla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dupla.any_instance.stub(:save).and_return(false)
        put :update, {:id => dupla.to_param, :dupla => { "nombre" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dupla" do
      dupla = Dupla.create! valid_attributes
      expect {
        delete :destroy, {:id => dupla.to_param}, valid_session
      }.to change(Dupla, :count).by(-1)
    end

    it "redirects to the duplas list" do
      dupla = Dupla.create! valid_attributes
      delete :destroy, {:id => dupla.to_param}, valid_session
      expect(response).to redirect_to(duplas_url)
    end
  end

end
