require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JuecesController do

  # This should return the minimal set of attributes required to create a valid
  # Juez. As you add validations to Juez, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "foto" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JuecesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all jueces as @jueces" do
      juez = Juez.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:jueces)).to eq([juez])
    end
  end

  describe "GET show" do
    it "assigns the requested juez as @juez" do
      juez = Juez.create! valid_attributes
      get :show, {:id => juez.to_param}, valid_session
      expect(assigns(:juez)).to eq(juez)
    end
  end

  describe "GET new" do
    it "assigns a new juez as @juez" do
      get :new, {}, valid_session
      expect(assigns(:juez)).to be_a_new(Juez)
    end
  end

  describe "GET edit" do
    it "assigns the requested juez as @juez" do
      juez = Juez.create! valid_attributes
      get :edit, {:id => juez.to_param}, valid_session
      expect(assigns(:juez)).to eq(juez)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Juez" do
        expect {
          post :create, {:juez => valid_attributes}, valid_session
        }.to change(Juez, :count).by(1)
      end

      it "assigns a newly created juez as @juez" do
        post :create, {:juez => valid_attributes}, valid_session
        expect(assigns(:juez)).to be_a(Juez)
        expect(assigns(:juez)).to be_persisted
      end

      it "redirects to the created juez" do
        post :create, {:juez => valid_attributes}, valid_session
        expect(response).to redirect_to(Juez.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved juez as @juez" do
        # Trigger the behavior that occurs when invalid params are submitted
        Juez.any_instance.stub(:save).and_return(false)
        post :create, {:juez => { "foto" => "invalid value" }}, valid_session
        expect(assigns(:juez)).to be_a_new(Juez)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Juez.any_instance.stub(:save).and_return(false)
        post :create, {:juez => { "foto" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested juez" do
        juez = Juez.create! valid_attributes
        # Assuming there are no other jueces in the database, this
        # specifies that the Juez created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Juez).to receive(:update).with({ "foto" => "MyString" })
        put :update, {:id => juez.to_param, :juez => { "foto" => "MyString" }}, valid_session
      end

      it "assigns the requested juez as @juez" do
        juez = Juez.create! valid_attributes
        put :update, {:id => juez.to_param, :juez => valid_attributes}, valid_session
        expect(assigns(:juez)).to eq(juez)
      end

      it "redirects to the juez" do
        juez = Juez.create! valid_attributes
        put :update, {:id => juez.to_param, :juez => valid_attributes}, valid_session
        expect(response).to redirect_to(juez)
      end
    end

    describe "with invalid params" do
      it "assigns the juez as @juez" do
        juez = Juez.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Juez.any_instance.stub(:save).and_return(false)
        put :update, {:id => juez.to_param, :juez => { "foto" => "invalid value" }}, valid_session
        expect(assigns(:juez)).to eq(juez)
      end

      it "re-renders the 'edit' template" do
        juez = Juez.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Juez.any_instance.stub(:save).and_return(false)
        put :update, {:id => juez.to_param, :juez => { "foto" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested juez" do
      juez = Juez.create! valid_attributes
      expect {
        delete :destroy, {:id => juez.to_param}, valid_session
      }.to change(Juez, :count).by(-1)
    end

    it "redirects to the jueces list" do
      juez = Juez.create! valid_attributes
      delete :destroy, {:id => juez.to_param}, valid_session
      expect(response).to redirect_to(jueces_url)
    end
  end

end
