require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReglamentosController do

  # This should return the minimal set of attributes required to create a valid
  # Reglamento. As you add validations to Reglamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "titulo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReglamentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all reglamentos as @reglamentos" do
      reglamento = Reglamento.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:reglamentos)).to eq([reglamento])
    end
  end

  describe "GET show" do
    it "assigns the requested reglamento as @reglamento" do
      reglamento = Reglamento.create! valid_attributes
      get :show, {:id => reglamento.to_param}, valid_session
      expect(assigns(:reglamento)).to eq(reglamento)
    end
  end

  describe "GET new" do
    it "assigns a new reglamento as @reglamento" do
      get :new, {}, valid_session
      expect(assigns(:reglamento)).to be_a_new(Reglamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested reglamento as @reglamento" do
      reglamento = Reglamento.create! valid_attributes
      get :edit, {:id => reglamento.to_param}, valid_session
      expect(assigns(:reglamento)).to eq(reglamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reglamento" do
        expect {
          post :create, {:reglamento => valid_attributes}, valid_session
        }.to change(Reglamento, :count).by(1)
      end

      it "assigns a newly created reglamento as @reglamento" do
        post :create, {:reglamento => valid_attributes}, valid_session
        expect(assigns(:reglamento)).to be_a(Reglamento)
        expect(assigns(:reglamento)).to be_persisted
      end

      it "redirects to the created reglamento" do
        post :create, {:reglamento => valid_attributes}, valid_session
        expect(response).to redirect_to(Reglamento.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reglamento as @reglamento" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reglamento.any_instance.stub(:save).and_return(false)
        post :create, {:reglamento => { "titulo" => "invalid value" }}, valid_session
        expect(assigns(:reglamento)).to be_a_new(Reglamento)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reglamento.any_instance.stub(:save).and_return(false)
        post :create, {:reglamento => { "titulo" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reglamento" do
        reglamento = Reglamento.create! valid_attributes
        # Assuming there are no other reglamentos in the database, this
        # specifies that the Reglamento created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Reglamento).to receive(:update).with({ "titulo" => "MyString" })
        put :update, {:id => reglamento.to_param, :reglamento => { "titulo" => "MyString" }}, valid_session
      end

      it "assigns the requested reglamento as @reglamento" do
        reglamento = Reglamento.create! valid_attributes
        put :update, {:id => reglamento.to_param, :reglamento => valid_attributes}, valid_session
        expect(assigns(:reglamento)).to eq(reglamento)
      end

      it "redirects to the reglamento" do
        reglamento = Reglamento.create! valid_attributes
        put :update, {:id => reglamento.to_param, :reglamento => valid_attributes}, valid_session
        expect(response).to redirect_to(reglamento)
      end
    end

    describe "with invalid params" do
      it "assigns the reglamento as @reglamento" do
        reglamento = Reglamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reglamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => reglamento.to_param, :reglamento => { "titulo" => "invalid value" }}, valid_session
        expect(assigns(:reglamento)).to eq(reglamento)
      end

      it "re-renders the 'edit' template" do
        reglamento = Reglamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reglamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => reglamento.to_param, :reglamento => { "titulo" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reglamento" do
      reglamento = Reglamento.create! valid_attributes
      expect {
        delete :destroy, {:id => reglamento.to_param}, valid_session
      }.to change(Reglamento, :count).by(-1)
    end

    it "redirects to the reglamentos list" do
      reglamento = Reglamento.create! valid_attributes
      delete :destroy, {:id => reglamento.to_param}, valid_session
      expect(response).to redirect_to(reglamentos_url)
    end
  end

end
