require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StreamingsController do

  # This should return the minimal set of attributes required to create a valid
  # Streaming. As you add validations to Streaming, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "codigo_embed" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StreamingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all streamings as @streamings" do
      streaming = Streaming.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:streamings)).to eq([streaming])
    end
  end

  describe "GET show" do
    it "assigns the requested streaming as @streaming" do
      streaming = Streaming.create! valid_attributes
      get :show, {:id => streaming.to_param}, valid_session
      expect(assigns(:streaming)).to eq(streaming)
    end
  end

  describe "GET new" do
    it "assigns a new streaming as @streaming" do
      get :new, {}, valid_session
      expect(assigns(:streaming)).to be_a_new(Streaming)
    end
  end

  describe "GET edit" do
    it "assigns the requested streaming as @streaming" do
      streaming = Streaming.create! valid_attributes
      get :edit, {:id => streaming.to_param}, valid_session
      expect(assigns(:streaming)).to eq(streaming)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Streaming" do
        expect {
          post :create, {:streaming => valid_attributes}, valid_session
        }.to change(Streaming, :count).by(1)
      end

      it "assigns a newly created streaming as @streaming" do
        post :create, {:streaming => valid_attributes}, valid_session
        expect(assigns(:streaming)).to be_a(Streaming)
        expect(assigns(:streaming)).to be_persisted
      end

      it "redirects to the created streaming" do
        post :create, {:streaming => valid_attributes}, valid_session
        expect(response).to redirect_to(Streaming.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved streaming as @streaming" do
        # Trigger the behavior that occurs when invalid params are submitted
        Streaming.any_instance.stub(:save).and_return(false)
        post :create, {:streaming => { "codigo_embed" => "invalid value" }}, valid_session
        expect(assigns(:streaming)).to be_a_new(Streaming)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Streaming.any_instance.stub(:save).and_return(false)
        post :create, {:streaming => { "codigo_embed" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested streaming" do
        streaming = Streaming.create! valid_attributes
        # Assuming there are no other streamings in the database, this
        # specifies that the Streaming created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Streaming).to receive(:update).with({ "codigo_embed" => "MyString" })
        put :update, {:id => streaming.to_param, :streaming => { "codigo_embed" => "MyString" }}, valid_session
      end

      it "assigns the requested streaming as @streaming" do
        streaming = Streaming.create! valid_attributes
        put :update, {:id => streaming.to_param, :streaming => valid_attributes}, valid_session
        expect(assigns(:streaming)).to eq(streaming)
      end

      it "redirects to the streaming" do
        streaming = Streaming.create! valid_attributes
        put :update, {:id => streaming.to_param, :streaming => valid_attributes}, valid_session
        expect(response).to redirect_to(streaming)
      end
    end

    describe "with invalid params" do
      it "assigns the streaming as @streaming" do
        streaming = Streaming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Streaming.any_instance.stub(:save).and_return(false)
        put :update, {:id => streaming.to_param, :streaming => { "codigo_embed" => "invalid value" }}, valid_session
        expect(assigns(:streaming)).to eq(streaming)
      end

      it "re-renders the 'edit' template" do
        streaming = Streaming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Streaming.any_instance.stub(:save).and_return(false)
        put :update, {:id => streaming.to_param, :streaming => { "codigo_embed" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested streaming" do
      streaming = Streaming.create! valid_attributes
      expect {
        delete :destroy, {:id => streaming.to_param}, valid_session
      }.to change(Streaming, :count).by(-1)
    end

    it "redirects to the streamings list" do
      streaming = Streaming.create! valid_attributes
      delete :destroy, {:id => streaming.to_param}, valid_session
      expect(response).to redirect_to(streamings_url)
    end
  end

end
