require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VisasController do

  # This should return the minimal set of attributes required to create a valid
  # Visa. As you add validations to Visa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "titulo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VisasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all visas as @visas" do
      visa = Visa.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:visas)).to eq([visa])
    end
  end

  describe "GET show" do
    it "assigns the requested visa as @visa" do
      visa = Visa.create! valid_attributes
      get :show, {:id => visa.to_param}, valid_session
      expect(assigns(:visa)).to eq(visa)
    end
  end

  describe "GET new" do
    it "assigns a new visa as @visa" do
      get :new, {}, valid_session
      expect(assigns(:visa)).to be_a_new(Visa)
    end
  end

  describe "GET edit" do
    it "assigns the requested visa as @visa" do
      visa = Visa.create! valid_attributes
      get :edit, {:id => visa.to_param}, valid_session
      expect(assigns(:visa)).to eq(visa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Visa" do
        expect {
          post :create, {:visa => valid_attributes}, valid_session
        }.to change(Visa, :count).by(1)
      end

      it "assigns a newly created visa as @visa" do
        post :create, {:visa => valid_attributes}, valid_session
        expect(assigns(:visa)).to be_a(Visa)
        expect(assigns(:visa)).to be_persisted
      end

      it "redirects to the created visa" do
        post :create, {:visa => valid_attributes}, valid_session
        expect(response).to redirect_to(Visa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved visa as @visa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Visa.any_instance.stub(:save).and_return(false)
        post :create, {:visa => { "titulo" => "invalid value" }}, valid_session
        expect(assigns(:visa)).to be_a_new(Visa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Visa.any_instance.stub(:save).and_return(false)
        post :create, {:visa => { "titulo" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested visa" do
        visa = Visa.create! valid_attributes
        # Assuming there are no other visas in the database, this
        # specifies that the Visa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Visa).to receive(:update).with({ "titulo" => "MyString" })
        put :update, {:id => visa.to_param, :visa => { "titulo" => "MyString" }}, valid_session
      end

      it "assigns the requested visa as @visa" do
        visa = Visa.create! valid_attributes
        put :update, {:id => visa.to_param, :visa => valid_attributes}, valid_session
        expect(assigns(:visa)).to eq(visa)
      end

      it "redirects to the visa" do
        visa = Visa.create! valid_attributes
        put :update, {:id => visa.to_param, :visa => valid_attributes}, valid_session
        expect(response).to redirect_to(visa)
      end
    end

    describe "with invalid params" do
      it "assigns the visa as @visa" do
        visa = Visa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Visa.any_instance.stub(:save).and_return(false)
        put :update, {:id => visa.to_param, :visa => { "titulo" => "invalid value" }}, valid_session
        expect(assigns(:visa)).to eq(visa)
      end

      it "re-renders the 'edit' template" do
        visa = Visa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Visa.any_instance.stub(:save).and_return(false)
        put :update, {:id => visa.to_param, :visa => { "titulo" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested visa" do
      visa = Visa.create! valid_attributes
      expect {
        delete :destroy, {:id => visa.to_param}, valid_session
      }.to change(Visa, :count).by(-1)
    end

    it "redirects to the visas list" do
      visa = Visa.create! valid_attributes
      delete :destroy, {:id => visa.to_param}, valid_session
      expect(response).to redirect_to(visas_url)
    end
  end

end
